import Vue from 'vue'
import { Button, Switch, Tabbar, TabbarItem, NavBar, Toast, Swipe, SwipeItem, Grid, GridItem, Search, Icon, Lazyload, Rate, ActionSheet, Dialog, Checkbox, Tab, Tabs } from 'vant'
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Button)
Vue.use(Switch)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Checkbox)
Vue.use(Search)
Vue.use(Icon)
Vue.use(Rate)
Vue.use(ActionSheet)
Vue.use(Lazyload)
Vue.use(Toast)
Vue.use(Dialog)
